Update action

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -31,48 +31,64 @@ jobs:
         runs-on: ubuntu-latest
         if: ${{ github.repository == 'kikkomep/test-py-pipelines' }} # && github.event.workflow_run.conclusion == 'success' }}
         steps:
-            - name: Wait for tests to succeed
-              uses: lewagon/wait-on-check-action@v1.3.4
+            - name: Wait for build to succeed
+              uses: fountainhead/action-wait-for-check@v1.2.0
+              id: wait-for-build
               with:
-                ref: ${{ github.ref }}
-                check-name: 'Lint Python Code (Flake8)'
-                repo-token: ${{ secrets.GITHUB_TOKEN }}
-                wait-interval: 10
-            # Wait for the first workflow to finish
-            # Access the tag from the first workflow's outputs
-            - name: ⬇️ Checkout code
-              uses: actions/checkout@v4
-            - name: 🐍 Set up Python
-              uses: actions/setup-python@v5
-              with:
-                  python-version: "3.x"
-            - name: 🚧 Set up Python Environment
-              run: |
-                  pip install --upgrade pip
-                  pip install poetry
-            - name: 📦 Install Package Dependencies
-              run: poetry install --no-interaction --no-ansi
-            - name: ✅ Check version
-              run: |
-                  if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_type }}" == "tag" ]; then
-                    declared_version=$(poetry version -s)
-                    echo "Checking tag '${{ github.ref }}' against package version $declared_version"
-                    if [ "${{ github.ref }}" != "refs/tags/$declared_version" ]; then
-                      echo "Tag '${{ github.ref }}' does not match the declared package version '$declared_version'"
-                      exit 1
-                    else
-                      echo "Tag '${{ github.ref }}' matches the declared package version '$declared_version'"
-                    fi
-                  fi
-            - name: 🏗️ Build a binary wheel and a source tarball
-              run: poetry build
-            - name: 📦 Store the distribution packages
-              uses: actions/upload-artifact@v4
-              with:
-                  name: python-package-distributions
-                  path: |
-                      dist/*.whl
-                      dist/*.tar.gz
+                token: ${{ secrets.GITHUB_TOKEN }}
+                checkName: flake8
+                ref: ${{ github.sha }}
+      
+            - name: Do something with a passing build
+              if: steps.wait-for-build.outputs.conclusion == 'success'
+              run: echo "Build passed"
+      
+            - name: Do something with a failing build
+              if: steps.wait-for-build.outputs.conclusion == 'failure'
+              run: echo "Build failed"
+
+            # - name: Wait for tests to succeed
+            #   uses: lewagon/wait-on-check-action@v1.3.4
+            #   with:
+            #     ref: ${{ github.ref }}
+            #     check-name: 'Lint Python Code (Flake8)'
+            #     repo-token: ${{ secrets.GITHUB_TOKEN }}
+            #     wait-interval: 10
+            # # Wait for the first workflow to finish
+            # # Access the tag from the first workflow's outputs
+            # - name: ⬇️ Checkout code
+            #   uses: actions/checkout@v4
+            # - name: 🐍 Set up Python
+            #   uses: actions/setup-python@v5
+            #   with:
+            #       python-version: "3.x"
+            # - name: 🚧 Set up Python Environment
+            #   run: |
+            #       pip install --upgrade pip
+            #       pip install poetry
+            # - name: 📦 Install Package Dependencies
+            #   run: poetry install --no-interaction --no-ansi
+            # - name: ✅ Check version
+            #   run: |
+            #       if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_type }}" == "tag" ]; then
+            #         declared_version=$(poetry version -s)
+            #         echo "Checking tag '${{ github.ref }}' against package version $declared_version"
+            #         if [ "${{ github.ref }}" != "refs/tags/$declared_version" ]; then
+            #           echo "Tag '${{ github.ref }}' does not match the declared package version '$declared_version'"
+            #           exit 1
+            #         else
+            #           echo "Tag '${{ github.ref }}' matches the declared package version '$declared_version'"
+            #         fi
+            #       fi
+            # - name: 🏗️ Build a binary wheel and a source tarball
+            #   run: poetry build
+            # - name: 📦 Store the distribution packages
+            #   uses: actions/upload-artifact@v4
+            #   with:
+            #       name: python-package-distributions
+            #       path: |
+            #           dist/*.whl
+            #           dist/*.tar.gz
 
     # Publish to TestPyPI
     # publish-to-testpypi:
